package com.myspace.weatherapiexample;

function com.myspace.restapidemo.SampleData convertToSampleData (Object data){
        
        System.out.println(">>>>>> data = data");
        
        com.fasterxml.jackson.databind.ObjectMapper mapper = new com.fasterxml.jackson.databind.ObjectMapper();
        
        com.myspace.weatherapidemo.WeatherInfo sampleData = mapper.readValue(data.toString(), com.myspace.weatherapidemo.WeatherInfo.class);

        System.out.println(">>>>>> sampleData = sampleData");
        System.out.println(">>>>>> sampleData.ssn" + sampleData.getSsn());
		
		return sampleData;
		
}