package com.myspace.weatherapiexample;

function com.myspace.weatherapiexample.WeatherInfo convertJSONToObject (String data){
        
        System.out.println(">>>>>> data = data");
        
        com.fasterxml.jackson.databind.ObjectMapper mapper = new com.fasterxml.jackson.databind.ObjectMapper();
        
        com.myspace.weatherapiexample.WeatherInfo sampleData = mapper.readValue(data.toString(), com.myspace.weatherapiexample.WeatherInfo.class);

        System.out.println(">>>>>> sampleData = sampleData");
        System.out.println(">>>>>> sampleData.ssn" + sampleData.getName());
		
		return sampleData;
		
}