package com.myspace.weatherapiexample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Clouds implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "All")
	private float all;

	public Clouds() {
	}

	public float getAll() {
		return this.all;
	}

	public void setAll(float all) {
		this.all = all;
	}

	public Clouds(float all) {
		this.all = all;
	}

}