package com.myspace.weatherapiexample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Coordinates implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Coordinates() {
    }




}